/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.neusoft.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.neusoft.core.actionBase.ActionBase;
import com.neusoft.spring.services.TestService;

/** 
 * MyEclipse Struts
 * Creation date: 04-12-2009
 * 
 * XDoclet definition:
 * @struts.action parameter="Method" validate="true"
 */
public class TestAction extends ActionBase {

	
	public TestService testService;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward test(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws Exception {
		 if(log.isInfoEnabled()){
			 log.info("调用test");
		 }
		testService = (TestService)getBean("TestService");
		response.setCharacterEncoding("UTF-8");
		response.getWriter().write(testService.test());
		return null;
	}

}