/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.neusoft.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.neusoft.spring.services.TestService;

/** 
 * MyEclipse Struts
 * Creation date: 04-12-2009
 * 
 * XDoclet definition:
 * @struts.action parameter="Method" validate="true"
 */
public class TestAction extends DispatchAction {
	Log log = LogFactory.getLog(this.getClass());
	protected Object getBean(String beanid){
		Object result = null; 
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.servlet.getServletContext());
		 result= ctx.getBean(beanid);
		 if (result==null) {
			 if(log.isInfoEnabled()){
				 log.info("没有找到bean");
			 }
			 throw new RuntimeException("没有找到bean");
		 }
		 return result;
	}
	
	public TestService testService;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward test(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws Exception {
		 if(log.isInfoEnabled()){
			 log.info("调用test");
		 }
		testService = (TestService)getBean("TestService");
		response.setCharacterEncoding("UTF-8");
		response.getWriter().write(testService.test());
		return null;
	}

}